version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testRabbit
    ports:
      - "5432:5432"
    networks:
      - app-network

  golang-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-api
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - postgres
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      POSTGRES_URL: postgres://root:root@postgres:5432/testRabbit?sslmode=disable
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
